/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InputDataRouteImport } from './routes/input-data'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InputDataRoute = InputDataRouteImport.update({
  id: '/input-data',
  path: '/input-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/input-data': typeof InputDataRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/input-data': typeof InputDataRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/how-it-works': typeof HowItWorksRoute
  '/input-data': typeof InputDataRoute
  '/api/chat': typeof ApiChatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/input-data'
    | '/api/chat'
    | '/api/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/input-data'
    | '/api/chat'
    | '/api/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/how-it-works'
    | '/input-data'
    | '/api/chat'
    | '/api/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InputDataRoute: typeof InputDataRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input-data': {
      id: '/input-data'
      path: '/input-data'
      fullPath: '/input-data'
      preLoaderRoute: typeof InputDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HowItWorksRoute: HowItWorksRoute,
  InputDataRoute: InputDataRoute,
  ApiChatRoute: ApiChatRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
